#!/usr/bin/env bash

set -e

rootdir="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"
outfile="$rootdir/bin/create"

if [[ -n "$DEV_ENV" ]]; then
  if ! [[ $(go version) == *go1.9* ]]; then
    echo "Must have go 1.9"
    exit 1
  fi

  export GOPATH=$rootdir
  go build -o "$outfile" "$rootdir/src/create/main.go"
else
  version=$(cat "$rootdir/VERSION")
  url="https://s3.amazonaws.com/windows2016fs/create-binaries/create-$version-linux-amd64"

  mkdir -p "$rootdir/bin"
  curl --retry 15 --retry-delay 2 "$url" -o "$outfile" -L --fail -f
  chmod +x "$outfile"
fi

"$outfile" "$rootdir"
